### ISSUE TITLE
rpm-ostree compose for centos7 complains about missing repo

### ISSUE THREAD

**Issue by pkliczewski** [jasonbrooks/byo-atomic#2]
I follow the steps to build atomic image from scratch and during rpm-ostree compose I can see:

Error getting repository data for base, repository not found
error: Child process exited with code 1

I checked centos-atomic-base.json and noticed that repos defined in this file are not consistently separated by comma. I am not sure what is correct syntax since I was not able to find any reference.

**Comment by jasonbrooks** [comment]
If you're still encountering this issue, try running `nscd` before the rpm-ostree command. I've added this pkg to the dockerfile.
