### ISSUE TITLE
Unable to build qcow2 image on Fedora 21 Beta

### ISSUE THREAD

**Issue by CuriousA62A2A** [jasonbrooks/byo-atomic#3]
After following the README on https://github.com/jasonbrooks/byo-atomic (Optional: Create your own Atomic image to be exact).
Instead of shiny new images I get the error message below and a 512K f21-atomic.qcow2.tmp 

$ rpm-ostree-toolbox create-vm-disk /srv/rpm-ostree/repo fedora-atomic-host fedora-atomic/f21/x86_64/docker-host f21-atomic.qcow2
Formatting '/root/byo-atomic/fedora-atomic/f21-atomic.qcow2.tmp', fmt=qcow2 size=8589934592 compat='0.10' encryption=off cluster_size=65536 lazy_refcounts=off

(gjs:13836): Gjs-WARNING **: JS ERROR: ReferenceError: Format is not defined
createDisk@/usr/share/rpm-ostree-toolbox/js/libqa.js:132
CreateVmDisk<.execute@/usr/share/rpm-ostree-toolbox/js/builtins/create_vm_disk.js:62
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Builtin<.main@/usr/share/rpm-ostree-toolbox/js/builtin.js:41
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
@/usr/share/rpm-ostree-toolbox/js/main.js:85
@/usr/share/rpm-ostree-toolbox/js/main.js:92

**Comment by jasonbrooks** [comment]
Fixed? Also, I'll soon be updating the image-building part of this to work w/ the updated rpm-ostree-toolbox.
